apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-ubuntu.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "ssh-ubuntu.name" . }}
  ports:
    - name: ssh
      port: {{ .Values.ssh.port }}
      targetPort: {{ .Values.ssh.port }}

